### ISSUE TITLE
Add reflection parameter menu to PanelAttribute

### ISSUE THREAD

**Issue by ChrisPrusik** [G1ANT-Robot/G1ANT.Robot#2]
for example: 
1. Variables
2. Tools/Special

**Comment by MarcinMachowski** [comment]
Learning Panel need support for multiple menu items. Single Menu parameter in PanelAttribute class is not sufficient for that purpose. The parameter might be useful for placing menu item that will display panel.

Consider method-level MenuAttribute for defining action to be performed on different menus clicks.
