### ISSUE TITLE
Create LogToCsv.exe program

### ISSUE THREAD

**Issue by ChrisPrusik** [G1ANT-Robot/G1ANT.Robot#4]
Generate 'yyyy-MM-dd-HH-mm.csv' (today) file which will contain all tasks executions summary based on all '*.log' files from current directory and all subdirectories. For example:

2018-06-20\t50
2018-06-21\t45
2018-06-22\t20

**Comment by ChrisPrusik** [comment]
Is this ready? Close!

**Comment by WiktoriaPrusik** [comment]
yes, it's finished
